version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/github.com/Sakamoto0525/gRPC-Tutorial
    ports:
      -  8000:8000